"""ap_num nullable=False

Revision ID: 3c69c9e07743
Revises: f08be4c24c41
Create Date: 2024-06-23 10:09:48.120222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c69c9e07743'
down_revision = 'f08be4c24c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.alter_column('num',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.alter_column('num',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
