"""unique_constr_ap

Revision ID: 56ab68d931a8
Revises: bac3496ffaac
Create Date: 2024-06-22 18:31:19.716521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ab68d931a8'
down_revision = 'bac3496ffaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['resident_id', 'num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
