"""ONDELETE

Revision ID: 5c8a563c0576
Revises: dae09b0f6e61
Create Date: 2024-06-22 16:50:11.795686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8a563c0576'
down_revision = 'dae09b0f6e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint('apartments_resident_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'residents', ['resident_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint('cars_resident_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'residents', ['resident_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint('parking_slots_resident_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'residents', ['resident_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parking_slots_resident_id_fkey', 'residents', ['resident_id'], ['id'])

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('cars_resident_id_fkey', 'residents', ['resident_id'], ['id'])

    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('apartments_resident_id_fkey', 'residents', ['resident_id'], ['id'])

    # ### end Alembic commands ###
