"""plate_string_lenght

Revision ID: 6db1a9054dd2
Revises: 24780c8944fc
Create Date: 2024-06-23 01:16:47.801381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6db1a9054dd2'
down_revision = '24780c8944fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('plate',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.alter_column('plate',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
