"""parking slots without resident_id

Revision ID: 9508d1a4bb59
Revises: e3c500dc1d44
Create Date: 2024-06-22 21:02:27.082440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9508d1a4bb59'
down_revision = 'e3c500dc1d44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.alter_column('resident_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
