"""pass_info

Revision ID: a8875105c825
Revises: 5c8a563c0576
Create Date: 2024-06-22 17:11:35.651775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8875105c825'
down_revision = '5c8a563c0576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.alter_column('pas_series',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)
        batch_op.alter_column('pas_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.alter_column('pas_number',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('pas_series',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
