"""unique=True

Revision ID: bac3496ffaac
Revises: a8875105c825
Create Date: 2024-06-22 17:14:23.286324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac3496ffaac'
down_revision = 'a8875105c825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['plate'])

    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['pas_number'])
        batch_op.create_unique_constraint(None, ['pas_series'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
