"""pasport constraints

Revision ID: ce54ade67bfd
Revises: 3c69c9e07743
Create Date: 2024-06-23 10:17:06.158104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce54ade67bfd'
down_revision = '3c69c9e07743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_constraint('residents_pas_number_key', type_='unique')
        batch_op.drop_constraint('residents_pas_series_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_unique_constraint('residents_pas_series_key', ['pas_series'])
        batch_op.create_unique_constraint('residents_pas_number_key', ['pas_number'])

    # ### end Alembic commands ###
