"""patronymic

Revision ID: da99ccb317bd
Revises: f8daf7ce2baf
Create Date: 2024-06-22 19:07:46.210011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da99ccb317bd'
down_revision = 'f8daf7ce2baf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('patronymic', sa.String(length=50), nullable=False))
        batch_op.drop_column('surname')
        batch_op.drop_column('second_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('surname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('patronymic')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
