"""delete brend from car

Revision ID: e3c500dc1d44
Revises: b5ddba365e99
Create Date: 2024-06-22 20:51:07.071119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c500dc1d44'
down_revision = 'b5ddba365e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('brand')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
