"""appartment_num

Revision ID: f08be4c24c41
Revises: 6db1a9054dd2
Create Date: 2024-06-23 10:05:07.949103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f08be4c24c41'
down_revision = '6db1a9054dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['num'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apartments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('num')

    # ### end Alembic commands ###
