"""unique_constr_car_ps

Revision ID: f6e8d3b75219
Revises: 56ab68d931a8
Create Date: 2024-06-22 18:36:50.320682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e8d3b75219'
down_revision = '56ab68d931a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['resident_id', 'plate'])

    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['resident_id', 'num', 'letter'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
