"""parking_slots_uniq_constr

Revision ID: f8daf7ce2baf
Revises: f6e8d3b75219
Create Date: 2024-06-22 18:59:54.480687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8daf7ce2baf'
down_revision = 'f6e8d3b75219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint('parking_slots_resident_id_num_letter_key', type_='unique')
        batch_op.create_unique_constraint(None, ['num', 'letter'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parking_slots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('parking_slots_resident_id_num_letter_key', ['resident_id', 'num', 'letter'])

    # ### end Alembic commands ###
